### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by lioaslan** [pinojs/hapi-pino#104]
I try to run example code but I get 
```
TypeError: Cannot read property 'name' of undefined
    at internals.Server.register (D:\Coding\Projects\offshorevn\offshorevn-log-analysis\node_modules\@hapi\hapi\lib\server.js:427:42)
    at start (D:\Coding\Projects\offshorevn\offshorevn-log-analysis\index.js:29:16)    at Object.<anonymous> (D:\Coding\Projects\offshorevn\offshorevn-log-analysis\index.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)      
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```
Thanks for any helps

**Comment by mcollina** [comment]
Which version of Hapi are you using?

**Comment by lioaslan** [comment]
```
"@hapi/hapi": "^18.4.0",
"hapi-pino": "^6.3.0"
```

**Comment by mcollina** [comment]
I cannot reproduce, the example runs just fine.

**Comment by lioaslan** [comment]
I can run example by replace `require('.')` by `require("hapi-pino")`. Thanks for reply
