### ISSUE TITLE
Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by robinjoseph08** [pinojs/hapi-pino#20]
Using `hapi-pino` in our development and staging environments seem to be fine, but when we add it to production, every now and then, we see this error:

```
Debug: internal, implementation, error
    TypeError: Cannot read property 'info' of undefined
    at .<anonymous> (/app/node_modules/hapi-pino/index.js:86:19)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at handler (/app/node_modules/kilt/lib/index.js:54:44)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at internals.Request._finalize (/app/node_modules/hapi/lib/request.js:479:21)
    at /app/node_modules/hapi/lib/request.js:455:25
    at ServerResponse.end (/app/node_modules/hapi/lib/transmit.js:298:13)
    at ServerResponse.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:185:7)
    at finish (_http_outgoing.js:596:10)
    at afterWrite (_stream_writable.js:385:3)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Digging in a bit deeper, it seems like the [`onRequest` extension point](https://github.com/pinojs/hapi-pino/blob/1f411d7bccfeb0b6d3ecb47c27467ef8ee9af118/index.js#L58-L61) isn't being called so `request.logger` isn't being set. I'm not sure if there are certain situations where that extension point is skipped, but it seems problematic.

I'm using `hapi-pino@1.7.0` and `hapi@10.5.0`. Any ideas?

**Comment by mcollina** [comment]
I think you should update your hapi version to something more recent.

**Comment by robinjoseph08** [comment]
Hey @mcollina, it took a while, but I finally upgraded to v16.5.2 and it looks like the error is still happening. The only difference in the stance trace is that the error is being emitted through `podium` instead of `EventEmitter` which is to be expected from the upgrade.

**Comment by mcollina** [comment]
Can you send some code to reproduce your problem? Or maybe send a PR with a fix?

**Comment by davidmarkclements** [comment]
closing for now, assuming as fixed 

@robinjoseph08 if you still have an issue here, please reopen!
