### ISSUE TITLE
Cannot enable prettyPrint

### ISSUE THREAD

**Issue by zol** [pinojs/hapi-pino#36]
### Versions
```
"hapi-pino": "2.0.1"
"hapi":  "16.5.2"
"pino": "4.10.2"
```

### Error

```
$ ./node_modules/.bin/babel-node ./src/server.js 
/Users/zol/Source/chromatic/node_modules/pino/pino.js:278
  if (!isStdout && iopts.prettyPrint) throw Error('cannot enable pretty print when stream is not process.stdout')
                                      ^

Error: cannot enable pretty print when stream is not process.stdout
    at pino (/Users/zol/Source/chromatic/node_modules/pino/pino.js:278:45)
    at Object.register (/Users/zol/Source/chromatic/node_modules/hapi-pino/index.js:38:14)
    at Object.target [as register] (/Users/zol/Source/chromatic/node_modules/joi/lib/types/object/index.js:77:34)
    at each (/Users/zol/Source/chromatic/node_modules/hapi/lib/plugin.js:310:14)
    at iterate (/Users/zol/Source/chromatic/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/zol/Source/chromatic/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Server.internals.Plugin.register (/Users/zol/Source/chromatic/node_modules/hapi/lib/plugin.js:313:11)
    at registerPlugins (/Users/zol/Source/chromatic/services/queue/src/config/plugins.js:10:10)
    at Object.<anonymous> (/Users/zol/Source/chromatic/services/queue/src/server.js:24:1)
    at Module._compile (module.js:573:30)
```

### Code

```
server.register(
    {
      register: HapiPino,
      options: {
        name: 'queue',
        prettyPrint: true,
      },
    },
    err => {
      if (err) {
        throw err;
      }
    }
  );
```

**Comment by davidmarkclements** [comment]
closing for now, assuming as fixed

@zol if you still have an issue here please reopen!
