### ISSUE TITLE
 Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by Akumzy** [pinojs/hapi-pino#84]
I have been getting this error whenever I refresh my Apollo graphql playground and based on the error trace `request.logger` inside `tryAddEvent` function (request completes ) is undefined
```log
TypeError: Cannot read property 'info' of undefined
    at Object.listener (/home/akumzy/momo/planner-server/node_modules/hapi-pino/index.js:120:25)
    at module.exports.internals.Podium.internals.Podium.emit (/home/akumzy/momo/planner-server/node_modules/@hapi/podium/lib/index.js:224:107)
    at Request._finalize (/home/akumzy/momo/planner-server/node_modules/@hapi/hapi/lib/request.js:447:27)
    at Request._reply (/home/akumzy/momo/planner-server/node_modules/@hapi/hapi/lib/request.js:391:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mcollina** [comment]
Can you send a PR with a unit test?

**Comment by rayko92** [comment]
Hi, same errror here. Any fix/idea?

```
TypeError: Cannot read property 'info' of undefined
at Object.listener (/Core/node_modules/hapi-pino/index.js:125:20)
at module.exports.internals.Podium.internals.Podium.emit (/Core/node_modules/@hapi/podium/lib/index.js:224:107)
at Request._finalize (/Core/node_modules/@hapi/hapi/lib/request.js:447:27)
at Request._reply (/Core/node_modules/@hapi/hapi/lib/request.js:391:14)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I tried the #85 and work good. But I don't know if this is valid or not.

**Comment by Akumzy** [comment]
Yeah I've been very busy. I'll try and write a test for it and resubmit pr

**Comment by DiegoRBaquero** [comment]
Also getting this error. Why could this happen? somewhere between request and response `request.logger` is modified/replaced?

**Comment by ben833** [comment]
How to replicate:

1. in hapi server's options, set ```load: {
                sampleInterval: 1000,
                maxEventLoopDelay: 1
            }```
2. start the server
3. perform a manual API call for any route (e.g. using CURL/postman)

You get an error like this
```
{"level":30,"time":1580930988151,"pid":36837,"hostname":"Ben-Margolis-MacBook-Pro.local","tags":["load"],"data":{"eventLoopDelay":3.7898669838905334,"heapUsed":50385752,"rss":118018048},"v":1}
{"level":50,"time":1580930988164,"pid":36837,"hostname":"Ben-Margolis-MacBook-Pro.local","data":"unhandled rejection caught","v":1}
{"level":50,"time":1580930988167,"pid":36837,"hostname":"Ben-Margolis-MacBook-Pro.local","data":"Cannot read property 'info' of undefined","stack":"TypeError: Cannot read property 'info' of undefined\n    at Object.listener (/Users/ben.margolis/Sites/x/node_modules/hapi-pino/index.js:132:20)\n    at module.exports.internals.Podium.internals.Podium.emit (/Users/ben.margolis/Sites/x/node_modules/@hapi/podium/lib/index.js:227:107)\n    at Request._finalize (/Users/ben.margolis/Sites/x/node_modules/@hapi/hapi/lib/request.js:447:27)\n    at Request._reply (/Users/ben.margolis/Sites/x/node_modules/@hapi/hapi/lib/request.js:391:14)\n    at processTicksAndRejections (internal/process/task_queues.js:89:5)","type":"Error","v":1}
```
